package com.realdolmen.domain;

/**
 * Created by WVDAZ49 on 5/09/2016.
 */
public enum  MapperType {
    UNDEFINED,
    CUSTOMER_FLIGHTS,
    CUSTOMER_LOGIN,
    CUSTOMER_REGISTER,
    FLIGHT_TICKET_DETAILS,
    BOOKING_CREATE,
    AVAILABLEFLIGHTS
    BOOKING_OVERVIEW,
    TICKET_BOOKING_OVERVIEW,
    FLIGHT_BOOKING
}
